### ISSUE TITLE
mara-main containers is scrolled below the mara-page-header

### ISSUE THREAD

**Issue by ghost** [mara/mara-app#12]
The result is that if you try to set a table-head to be always visible (e.g. with http://mkoryak.github.io/floatThead/), it scrolls below the header and is invisible.

**Comment by ghost** [comment]
Another artefact is that the header is fixed on the page and does not move to the side when the menu is opened...

**Comment by martin-loetzsch** [comment]
Fixed in efbb9dd, 492cb9d, https://github.com/mara/mara-page/commit/48ca33d

requires either the use of the mara_page.bootstrap functions or a replication of that markup
