### ISSUE TITLE
more pythonic way to construct the app

### ISSUE THREAD

**Issue by ghost** [mara/mara-app#16]
Currently the creation of the apps and it's blueprints is intransparent:
Ifa blueprint was importat in any way, it is added to the app. That leads to funny code which basically imports a lot of stuff but never uses it.

This has some problems:
* Intelij organize imports will remove such imports
* It might happen that you import a helper lib which defines a blueprint and that blueprint will automatically appear in your app
* It's unpythonic:  [Explicit is better than implicit.](https://www.python.org/dev/peps/pep-0020/)

I would therefore like to make the app creation explicit by reworking the individual `MaraApp` auto-register functions to take an explicit argument. To make it possible for other packages to change their stuff, these packages should expose a `MARA_XXX = [<xx object>]` list. The app creation process is then:

```python
import mara_page
app = MaraApp()
app.register_blueprints(mara_page.MARA_BLUEPRINTS)
# or even this, which would look through the module and fetch all known 
# MARA_XXX and register them
app.register_package(mara_page)
```

This still keeps mara-app and mara-page completely independent

**Comment by jacopofar** [comment]
We switched to something similar, modules are now loaded based on the presence of the `MARA_XXX` keys for blueprints, click commands and so on, like [this](https://github.com/mara/mara-app/blob/master/mara_app/app.py#L41).

This is currently done by introspection over the loaded modules, we plan to move to an even more explicit declaration like the one you described.

**Comment by martin-loetzsch** [comment]
I think with the `MARA_XXX` module variables we have now something that is halfway between registering everything that was imported and `register_package`.
