### ISSUE TITLE
makefile: always rebuilds the venv

### ISSUE THREAD

**Issue by ghost** [mara/mara-app#19]
The problem happens because the makefile is newer than the `.venv/bin/python` and therefore make thinks it has to rebuild the venv:

```
$ make -d update-packages
[...]
Obtained token for child 0x5620aea2f260 (.ensure-pushed-mara-db).
Putting child 0x5620aea2f260 (.ensure-pushed-mara-db) PID 18057 on the chain.
    Recipe of '.ensure-pushed-mara-db' is being run.
   Finished prerequisites of target file 'check-for-uncommitted-changes'.
  The prerequisites of 'check-for-uncommitted-changes' are being made.
  Considering target file '.venv/bin/python'.
    Pruning file 'Makefile'.
   Finished prerequisites of target file '.venv/bin/python'.
   Prerequisite 'Makefile' is newer than target '.venv/bin/python'.
  Must remake target '.venv/bin/python'.
[...]
```

I patch my venv after the creation to get a better pip experience (http://janschulz.github.io/workaround-for-problems-with-pip.html) and this basically undoes it evry time.

I see two ways to fix this: 
* use the `.venv/bin/activate`  (which is written to during the creation) or a `touch .venv/stampfile` as the dependency
* add my way of resolving the pip mess after the venv creation

I'm currently doing the latter in my local copy of the makefile:

```
	.venv/bin/pip install --upgrade pip setuptools pipdeptree wheel requests
	rm -v .venv/share/python-wheels/{requests,chardet,urllib3}-*.whl
```

**Comment by martin-loetzsch** [comment]
I'd be happy to have those two lines in the mara app Makefile. 

At some point we want to move to pipenv anyway.

**Comment by jacopofar** [comment]
I put this config in a project using mara and it works there, too.

Where should we publish this Makefile ?

**Comment by ghost** [comment]
I think an example project would be nice :-) I would be happy to put the pricing 'input data qa' page into it's own project and publish that as an example. (we probably end up with that anyway as we want to keep that functionality when pricing is moved over to java)

**Comment by martin-loetzsch** [comment]
I have an example project. Will show you next week
