### ISSUE TITLE
make update-packages does not work with pip 19.x.x

### ISSUE THREAD

**Issue by hendrikmakait** [mara/mara-app#28]
pip 19.0.0 dropped support for `--process-dependency-links` and therefore breaks `make update-packages`.

```
update-packages: PYTHONWARNINGS="ignore" .venv/bin/pip install --requirement=requirements.txt --src=./packages --upgrade --process-dependency-links --exists-action=w
update-packages: 
update-packages: Usage:   
update-packages:   pip install [options] <requirement specifier> [package-index-options] ...
update-packages:   pip install [options] -r <requirements file> [package-index-options] ...
update-packages:   pip install [options] [-e] <vcs project url> ...
update-packages:   pip install [options] [-e] <local project path> ...
update-packages:   pip install [options] <archive url/path> ...
update-packages: 
update-packages: no such option: --process-dependency-links
```

https://github.com/mara/mara-app/blob/c981f59f370588a25ebed990ee15ec1dbb72efbf/.scripts/install.mk#L22

See https://github.com/pypa/pip/issues/6162 for a discussion of the issue and possible solutions.

**Comment by jankatins** [comment]
I think everything else but this package is now uploaded as a pypi package, so we do not need dependency links anymore.

**Comment by martin-loetzsch** [comment]
A while ago we pinned `pip` to version 18.1 for that reason:
https://github.com/mara/mara-app/commit/8d1c87c76d3c3e53f51c2972a42fab27b75151cf

It's weird that you are seeing this.

Anyway, now that we have most of the stuff on Pypi, we can get rid of the dependency links and unpin `pip` (I'll do that).

**Comment by martin-loetzsch** [comment]
Fixed in https://github.com/mara/mara-app/commit/08174196221a4d77b84f5b3ec77c8a5e53298408
