### ISSUE TITLE
Missing static files in pypi package

### ISSUE THREAD

**Issue by alexeyegorov** [mara/mara-app#35]
As I can see the missing static files in the setup file have been fixed. However, there is no release of that version on PyPi. That would be great in order to be able to install mara-app as a complete package. :)

**Comment by leo-schick** [comment]
@alexeyegorov I created a new version, but can't create a new PyPi package since I don't have access to the pypi account. Maybe @martin-loetzsch could help with that?

**Comment by alexeyegorov** [comment]
Hey, 
thanks for your effort. We actually already gave up with this attempt. I think Martin is the one person having access and he is not available. We are currently on the way to switch from Mara slowly completely to Databricks, DBT and Fivetran. ;) But if you will be able to update the package, feel free to comment. We will then update our package within Mara. :)

**Comment by leo-schick** [comment]
@alexeyegorov I will make now a last attempt to contact @martin-loetzsch. Maybe you could try to contact him via LinkedIn as well. In case he doesn't respond, I will create a request at pypi.org to transfer ownership of the mara packages.
In case he still wants to have ownership but doesn't want to contribute, he could add someone of the community as maintainer (see https://pypi.org/help/#administration ).

**Comment by leo-schick** [comment]
@alexeyegorov I got now access to PyPi from Martin and published the package: [mara-app==2.2.1](https://pypi.org/project/mara-app/2.2.1/)

**Comment by alexeyegorov** [comment]
Thanks for finishing this up! :)
