### ISSUE TITLE
mara config page shows passwords

### ISSUE THREAD

**Issue by ghost** [mara/mara-app#9]
If a database config contains passwords, the password might be shown (e.g. for sql server: `Engine(mssql+pyodbc:///?odbc_connect=DRIVER=ODBC Driver 13 for SQL Server;UID=user;PWD=PASSWORD;SERVER=x.x.x.x;PORT=1433;DATABASE=db;)`).

In it's current form, the page should at least be hidden behind the admin resource.

**Comment by martin-loetzsch** [comment]
Solved by hiding behind ACL
